apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deployment #name of your deployment
spec: #this spec decribes your desired end state.
  replicas: 1 #1 pod
  selector:
    matchLabels:
      app: k8s-app #field defines how the Deployment finds which Pods to manage, set matching label in template.metadata.labels
  template: 
    metadata: 
      labels:
        app: k8s-app #label to define the pods to be managed by the deployment. Matches the spec.selector
    spec: #spec of your container that the pod manages
      containers:
        - name: node-app
          image: oliviajdunnett/k8s-tutorial:latest
          imagePullPolicy: Always # anytime you do a deployment this will always pull the lates image from the registry
          livenessProbe: # custom healthcheck - ping the app every 10 seconds, first call delayed by 5
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image: ...  you can add more than 1 container in the deployment
