apiVersion: v1
kind: Service
metadata:
  name: k8s-tutorial-service
  labels:
    group: k8s-app-deployment
spec:
  selector: 
    app: k8s-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer