apiVersion: v1
kind: Service
metadata:
  name: k8s-tutorial-service #name of your service
spec:
  selector: 
    app: k8s-app  # target pods by this label to manage them and route traffic to 
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer